/var/lib/condor/execute/dir_2710881/condor_ml.sh: line 44: 4: No such file or directory
WARNING:root:FRNN is not available, install it at https://github.com/murnanedaniel/FRNN. Using PyG radius instead.
Traceback (most recent call last):
  File "/local/anaconda3/envs/cosmicgnn/bin/acorn", line 33, in <module>
    sys.exit(load_entry_point('acorn', 'console_scripts', 'acorn')())
  File "/local/anaconda3/envs/cosmicgnn/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/local/anaconda3/envs/cosmicgnn/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/local/anaconda3/envs/cosmicgnn/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/local/anaconda3/envs/cosmicgnn/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/local/anaconda3/envs/cosmicgnn/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/misc/home/mue/karres/git/Mu3eCosmicGNN/acorn/core/entrypoint_stage.py", line 31, in infer
    infer_stage.infer(config_file, verbose, checkpoint)
  File "/misc/home/mue/karres/git/Mu3eCosmicGNN/acorn/core/infer_stage.py", line 59, in infer
    with open(config_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mu3e_cosmic_reader_v2.yaml'
